#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "myip"
name = "My IP"

description.en = "Small utility to provide &#34;what&#39;s my IP&#34; service"
description.fr = "Petit utilitaire pour fournir un service &#34;quelle est mon IP&#34;"

version = "1.0~ynh1"

maintainers = ["salamandar"]

[upstream]
license = "AGPL-3.0"
website = "https://ip.yunohost.org"
demo = "https://ip.yunohost.org"

code = "https://github.com/YunoHost-Apps/myip_ynh"

[integration]
yunohost = '>= 11.2.30'
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.permissions]
    main.url = "/"
